# Site settings
title: Web 3DVG
email: avioly@esad-orleans.fr
description: > # this means to ignore newlines until "baseurl:"
  L’objectif du cours, sur un semestre, est de découvrir — par la pratique — les fondamentaux du web.
  Il vise à donner aux étudiants des moyens de comprendre, mettre en œuvre une page web.
  Il sera complémentaire aux séances dirigées par Nicolas Tilly.
baseurl: "/3dvg-web" # the subpath of your site, e.g. /blog/
url: "http://esad-orleans.github.io" # the base hostname & protocol for your site
twitter_username: ESADOrleans
github_username:  esad-orleans

# Build settings
markdown: kramdown
